# Shared Makefile for all the platforms.
# Provides a way of building the lib with little brains.

all:
	@echo Dont call this file directly.
	@false

platform: $(OBJ)
	mkdir -p $(TOPDIR)/build/$(PLAT)
	cp $(OBJ) $(TOPDIR)/build/$(PLAT)
	cd $(TOPDIR)/build/$(PLAT); ls $(OBJ) > $(PLAT).lib

clean:
	rm -f $(OBJ) $(CLEANSPEC)
