# Shared Makefile for all the ports.
# Provides a way of building the lib with little brains.

all:
	@echo error: Dont call this file directly.
	@false

# Note that port.lib is setup by the calling Makefile
port: $(OBJ)
	mkdir -p $(TOPDIR)/build/$(PORT)
	cp $(OBJ) $(TOPDIR)/build/$(PORT)
	cd $(TOPDIR)/build/$(PORT); ls $(OBJ) >> $(PORT).lib

clean:
	rm -f $(OBJ) $(CLEANSPEC)
	cd ..; rm -f $(CLEANSPEC)
